### ISSUE TITLE
Upgrade to support Laravel 9

### ISSUE THREAD

**Issue by EddieOrbit** [gnello/laravel-mattermost-driver#5]
Can you update this package for support Laravel 9?

`"illuminate/support": "^5.0||^6.0||^7.0|^8.0|^9.0"`

**Comment by gnello** [comment]
Hi @EddieOrbit,
I've added support to Laravel 9 and did some tests, it works fine to me :)

I close this issue, please open a new one if something goes wrong with Laravel 9.
Thanks!
